### ISSUE TITLE
Dá para fazer uma taboada igual a de for em while?

### ISSUE THREAD

**Issue by VLHIDDEN** [cami-la/loops-e-arrays#1]
Olá professora tentei criar uma taboada usando while porém não deu muito certo.
https://github.com/VLHIDDEN/Tabuada_java_while_E_For
Se possivel dê uma olhada, ela retorna a respota correta porém não em lista.

**Comment by cami-la** [comment]
> Olá professora tentei criar uma taboada usando while porém não deu muito certo. https://github.com/VLHIDDEN/Tabuada_java_while_E_For Se possivel dê uma olhada, ela retorna a respota correta porém não em lista.

Olá, bom dia. (:

Você está colocando as impressões dentro do `while() `e também tem uma variável `a` que é desnecessária.
Dá uma analisada nessa forma que eu fiz e me diz se tem alguma dúvida:

```
System.out.println("Tabuada: ");
int tabuadaJS = scan.nextInt();

int i = 1;
System.out.println("Tabuada de " + tabuadaJS);
while (i <= 10) {
    System.out.println(tabuadaJS + " X " + i + " = " + (tabuadaJS * i));
    i = i + 1;
}
```
