### ISSUE TITLE
Ex3_MaiorEMedia.java

### ISSUE THREAD

**Issue by cassiafg** [cami-la/loops-e-arrays#33]
Boa tarde, Camila!
No exercício MaiorEMedia, como atribuímos 0 para a variável Maior o programa não é capaz de identificar o maior número se utilizarmos números negativos. Como podemos adaptar o código para funcionar também para números negativos?

**Comment by cami-la** [comment]
Oi @cassiafg tudo bem?

Respondi uma duvida parecida com a sua aqui: https://github.com/cami-la/loops-e-arrays/issues/21#issuecomment-1186478611

Veja se te ajuda. Caso não, pode falar que te explico de outra forma. (:

**Comment by cassiafg** [comment]
Ajudou sim! Muito obrigada :D
