### ISSUE TITLE
Exercício com titulo errado

### ISSUE THREAD

**Issue by danielgomees** [cami-la/loops-e-arrays#5]
O titulo do primeiro exercício do **WHILE** não condiz com o enunciado, poderia checar por favor?
[WHILE](https://github.com/cami-la/loops-e-arrays#-while)
Estava me causando confusão mas localizei na lista deste link [Lista de Estruturas de Repetição](https://wiki.python.org.br/EstruturaDeRepeticao), no exercício 39, e entendi.
@cami-la

**Comment by cami-la** [comment]
> 

Oi, amigão. Bom dia (
Não entendi bem o quetionamento, mas vou te passar o link dos exercícios resolvidos. Inclusive estão comentados.

[](https://github.com/cami-la/loops-e-arrays/tree/master/src/br/com/dio/exercicios)

**Comment by danielgomees** [comment]
Oi Camila
Então só estava tentando dizer que no primeiro exercício do WHILE, **Nome e Idade**, acho que esse titulo está confuso já que o enunciado pede altura e matricula, por exemplo.

**Comment by cami-la** [comment]
> Oi Camila Então só estava tentando dizer que no primeiro exercício do WHILE, **Nome e Idade**, acho que esse titulo está confuso já que o enunciado pede altura e matricula, por exemplo. Só comentei porque pode estar causando confusão em outros alunos também.

Aaaah, agora eu entendi.
No caso, o enunciado exercício de **Nome e Idade** estava descrito no README.md pedindo **altura e matrícula**. 

Pronto, agora consertei. Peguei o mesmo enunciado que está comentado no exercício e corrigi! (:

Em relação ao seu feedback, é muito importante! Sempre que achar algo que acredita ser um erro ou alguma sugestão de melhoria sinta-se à vontade. Essa área de issue serve para isso.

Na verdade, eu não tinha entendido mesmo o erro que você estava indicando. Mas agora está tudo certo.
Se tiver algo mais, fico à disposição.

**Comment by danielgomees** [comment]
Perfeito Camila, muito obrigado!!
