### ISSUE TITLE
dúvida do exercício 2: Nota

### ISSUE THREAD

**Issue by ghost** [cami-la/loops-e-arrays#51]
Olá Camila.  Como faço pra validar se o usuário digitar uma nota decimal? Fiz usando tipo double, mas não esta dando mais a mensagem "Nota inválida" ao digitar numero abaixo de 0 e maior que 10, está imprimindo essas notas tb.

![image](https://user-images.githubusercontent.com/114360730/230227664-8c40de4a-e5a8-4871-a58f-e6a3f9587d62.png)

**Comment by cami-la** [comment]
Oi, amigo. Tudo certinho?
Me dá um exemplo? Porque estou informando números menores que 0 e maiores que 10, sendo decimal e está dando certo:

![notas](https://user-images.githubusercontent.com/64323124/232482300-7ba92389-9df2-4c84-bc76-8420e8f56990.png)

**Comment by ghost** [comment]
Deu certo, obrigado.
