### ISSUE TITLE
Dúvida do exercício 1: Nome e idade

### ISSUE THREAD

**Issue by ghost** [cami-la/loops-e-arrays#52]
Camila, neste exercício se quisermos  validar que só possa ser digitado no campo "nome" STRING e no campo "idade" INT e sem valor negativo, como faz?

Tentei usar o método try catch para evitar que digitem String no campo idade, mas não deu certo.  Continua dando erro se digitar letras no campo idade.

![image](https://user-images.githubusercontent.com/114360730/230237096-af97478c-330b-4c4f-bf97-ac7ab2ebe32d.png)

**Comment by cami-la** [comment]
Sobre o nome ser `String`, é só definir a variável nome como `String`, aí não aceita nenhum outro tipo.
Sobre a idade, você pode fazer uma verificação, por exemplo: `if (idade < 0) faz a verificação`

Deu para entender?

**Comment by ghost** [comment]
Obrigado Camila.
