### ISSUE TITLE
Ex2_Nota - Nova Abordagem

### ISSUE THREAD

**Issue by jvmarquesvm** [cami-la/loops-e-arrays#7]
- Notei que o enunciado não está exatamente como foi desenvolvido. 
- Apresento uma nova abordagem para sua avalição.
- E para sair do programa só digitar -1.

`package br.com.dio.loops;

import java.util.Scanner;

/**
 * Faça um programa que peça uma nota, entre zero e dez.
 * Mostre uma mensagem caso o valor seja inválido e continue
 * pedindo até que o usuário informe um valor válido
 */
public class Nota {
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        Integer nota = 0;

        while ( nota != -1 ){
            System.out.println("Digite sua nota: ");
            nota = scan.nextInt();
            if ( !(nota >= 0 && nota <= 10) ){
                System.out.println("Digite uma nota entre 0 e 10");
            }
        }
    }
}
`
Qualquer observação.. só falar.
Obrigado!

**Comment by cami-la** [comment]
Oi, amigo. Tudo bem?
Olha, seu código está e looping infinito. :/ Tenta rodar ele aí na sua máquina.

Tomei a liberdade de dar uma modificada no seu código:

```java
public class Main2 {
  public static void main(String[] args) {
    Scanner scan = new Scanner(System.in);

    int nota = 0;
    if (nota != -1) {
      System.out.println("Digite sua nota: ");
      nota = scan.nextInt();

      //Verifique se a nota foi digitada corretamente
      while (!(nota >= 0 && nota <= 10)) {
        System.out.println("Numero inválido, tente novamente: ");
        nota = scan.nextInt();
      }
    }
  }
}
```

**Comment by jvmarquesvm** [comment]
Olá! Rodei e não verifiquei loop, mas com certeza essa sua modificação melhorou ainda mais e obtive a seguinte saída
Digite sua nota: 
0
Digite sua nota: 
2
Digite sua nota: 
39
Digite uma nota entre 0 e 10
Digite sua nota: 
3
Digite sua nota: 
2
Digite sua nota: 
4
Digite sua nota: 
2
Digite sua nota: 
-1
Digite uma nota entre 0 e 10

**Comment by cami-la** [comment]
> Olá! Rodei e não verifiquei loop, mas com certeza essa sua modificação melhorou ainda mais e obtive a seguinte saída Digite sua nota: 0 Digite sua nota: 2 Digite sua nota: 39 Digite uma nota entre 0 e 10 Digite sua nota: 3 Digite sua nota: 2 Digite sua nota: 4 Digite sua nota: 2 Digite sua nota: -1 Digite uma nota entre 0 e 10

Ah sim, entendi.
Perdão, esqueci de digitar -1 para sair do laço. Por isso achei que estava em looping infinito, Falha minha!
É só trocar o **if** por **while**.

```java
public class Main2 {
  public static void main(String[] args) {
    Scanner scan = new Scanner(System.in);

    int nota = 0;
    while (nota != -1) {
      System.out.println("Digite sua nota: ");
      nota = scan.nextInt();

      //Verifique se a nota foi digitada corretamente
      while (!(nota >= 0 && nota <= 10)) {
        System.out.println("Numero inválido, tente novamente: ");
        nota = scan.nextInt();
      }
    }
  }
}
```
